version: "3.9"
services:
  geth-init:
    image: "ethereum/client-go:latest"
    container_name: geth-init
    networks:
      - da_validator
    command: --datadir=/execution --cache.preimages --state.scheme=hash --verbosity=3 init /metadata/genesis.json
    volumes:
      - ./execution:/execution
      - ./metadata:/metadata

  geth:
    image: "ethereum/client-go:latest"
    container_name: geth
    restart: on-failure
    networks:
      - da_validator
    command:
      - --datadir=/execution
      - --http
      - --http.api=eth,net,web3,engine
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts=*
      - --http.corsdomain=*
      - --authrpc.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/metadata/jwtsecret
      - --identity=YourNameHere # Change With Your Validator Name
      - --networkid=293
      - --syncmode=full
      - --cache=1028
      - --rpc.allow-unprotected-txs
      - --port=30303
      - --gcmode=archive
      - --cache.preimages
      - --crypto.kzg=gokzg
      - --bootnodes=enode://6bd1871e8cdc8e566a6634d751e73d6db3decdd045649584647af89a673823721f9c910491d2f7bb9304ba0c6ba2fe9a3ade0fb1a67325a20e5ca0ec1b23d9b6@185.218.126.196:30303
    ports:
      - 8551:8551 # rpc engine
      - 8545:8545 # rpc json
      - 30303:30303/tcp # bootnodes
      - 30303:30303/udp # bootnodes
    depends_on:
      geth-init:
        condition: service_completed_successfully
    volumes:
      - ./execution:/execution
      - ./metadata:/metadata

  lighthouse_cl:
    image: "sigp/lighthouse:v5.2.1"
    container_name: lighthouse_cl
    restart: on-failure
    networks:
      - da_validator
    command:
      - lighthouse
      - bn
      - --gui
      - --eth1
      - --staking
      - --http
      - --http-port=5052
      - --http-allow-sync-stalled 
      - --http-address=0.0.0.0
      - --subscribe-all-subnets
      - --http-allow-origin=*
      - --debug-level=info
      - --datadir=/consensus
      - --testnet-dir=/metadata
      - --disable-enr-auto-update
      - --enr-address=0.0.0.0
      - --enr-udp-port=9000
      - --enr-tcp-port=9000
      - --discovery-port=9000
      - --port=9002
      - --target-peers=400
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5054
      - --graffiti=YourNameHere # Change With Your Validator Name
      - --execution-endpoints=http://geth:8551
      - --execution-jwt=/metadata/jwtsecret
      - --boot-nodes=-L64QKCtQXLwqMmsc94UgrlHFlW3gIl0nUbzKhWmZoMdF0pPRcnjr-WdJO6hYZp1YgifLUdm015JYqaeRS8MBWYiWT6BjIdhdHRuZXRziP__________hGV0aDKQ9KdRWWAAApPQBwAAAAAAAIJpZIJ2NIJpcIQm8smdhHF1aWOCIymJc2VjcDI1NmsxoQN-9-j23H3JS4tj5qgIB_MCLG8TQmZz_su-IW_ZZ0gzOYhzeW5jbmV0cw-DdGNwgiMo
    depends_on:
      geth:
        condition: service_started
    ports:
      - 5052:5052 # Ethereum Node Record
      - 5054:5054 # Metrics
      - 9000:9000/tcp # ENR port tcp
      - 9000:9000/udp # ENR port udp
    volumes:
      - ./consensus:/consensus
      - ./metadata:/metadata

  lighthouse_init:
    image: "sigp/lighthouse:v4.5.0"
    container_name: lighthouse_init
    networks:
      - da_validator
    command: 
      - lighthouse
      - account
      - validator
      - import
      - --testnet-dir=/metadata
      - --datadir=/validator
      - --directory=/validator_keys
      - --password-file=/metadata/password.txt
      - --reuse-password
    volumes:
      - ./metadata:/metadata
      - ./validator:/validator
      - ./validator_keys:/validator_keys

  lighthouse_vc:
    image: "sigp/lighthouse:v4.5.0"
    container_name: lighthouse_vc
    restart: on-failure
    networks:
      - da_validator
    command:
      - lighthouse
      - vc
      - --datadir=/validator
      - --testnet-dir=/metadata
      - --http
      - --http-address=0.0.0.0
      - --http-port=5062
      - --http-allow-origin=*
      - --unencrypted-http-transport
      - --init-slashing-protection
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-port=7073
      - --metrics-allow-origin=*
      - --suggested-fee-recipient=0x600795c1f15A9741E0378eb303e22c446B3dDd41 # Change With Your Address
      - --graffiti=YourNameHere # Change With Your Validator Name
      - --beacon-nodes=http://lighthouse_cl:5052
      - --logfile-max-size=10
    volumes:
      - ./metadata:/metadata
      - ./validator:/validator
    ports:
      - 5062:5062
      - 5064:5064
    depends_on:
      lighthouse_init:
        condition: service_completed_successfully
      lighthouse_cl:
        condition: service_started
      geth:
        condition: service_started

networks:
  da_validator:
    driver: bridge